# .streamlit/secrets.toml
cookie_password = "uma-frase-bem-grande-e-dificil"
auth_secret = "outro-segredo-muito-grande-e-aleatorio"

[usuarios]
Joao = "LibraJP"
Estevan = "14785236"
Breno = "LibraDRE2025"
Juan = "LibraJM"
Nelson = "LibraDRE2025"
Leonardo = "Leo@2025"
Greg = "Greg@2025"
Carlos = "Carlos@123"
Erico = "Erico2025"